title: HomeRobot: Open-Vocabulary Mobile Manipulation
description: HomeRobot (noun): An affordable compliant robot that navigates homes and manipulates a wide range of objects in order to complete everyday tasks.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
